system:
  env: DEV
domain:
  url: https://dev.priros.co.kr

page:
  default:
    title: PRIROS [DEV]

spring:
  jwt:
    secret:
      key: "weewqeqweqwe34ft24tgsgg2wqeqweqweqweqklnklqjeiqheklqwjwlekjqwlejlqjelqwjlejqkljekljq4"

temp:
  file:
    path: /usr/local/data/priros/files/upload/temp/
rm:
  case:
    document:
      file:
        path: /usr/local/data/priros/files/upload/rmcase/
  document:
    file:
      path: /usr/local/data/priros/files/upload/rm/
    annexment:
      filename: /usr/local/data/priros/files/doc/ANNEXMENT_PAPER.pdf
  real:
    estate:
      file:
        path: /usr/local/data/priros/files/upload/realestate/

firm:
  license:
    file:
      path: /usr/local/data/priros/files/upload/license/
  user:
    profile:
      file:
        path: /usr/local/data/priros/files/upload/profile/
board:
  upload:
    file:
      path: /usr/local/data/priros/files/upload/board/
consult:
  upload:
    file:
      path: /usr/local/data/priros/files/upload/consult/
inquiry:
  upload:
    file:
      path: /usr/local/data/priros/files/upload/inquiry/
request:
  report:
    upload:
      file:
        path: /usr/local/data/priros/files/upload/requestreport/

buybond:
  longin:
    userid: testuser02
    password: asdf!234
  base:
    url: https://test-dlaw.ktnet.com/new/app/

mail:
  smtp:
    host: smtp.gmail.com
    port: 465
  pop:
    host: pop.gmail.com
    port: 995
  user: priros.rpa@gmail.com
  password: yevzhmvhhkfgojsy
  regist:
    user:
      url: https://dev.priros.co.kr/main/registUser.rm?cmd=
    file:
      name: /usr/local/data/priros/files/mail/registUser.html

alim:
  regist:
    user:
      url: https://dev.priros.co.kr/main/registUser.rm?cmd=
  estimate:
    url: https://dev.priros.co.kr/link/estimate.rm?cmd=
  repay:
    url: https://dev.priros.co.kr/link/repay.rm?cmd=
  charge:
    url: https://dev.priros.co.kr/link/charge.rm?cmd=
  main:
    url: https://dev.priros.co.kr
  matching:
    url: https://dev.priros.co.kr/link/matching.rm?cmd=
  firm:
    review:
      url: https://dev.priros.co.kr/link/clientReview.rm?cmd=
  profile:
    refused:
      url: https://dev.priros.co.kr/main/helpCenterFaq.rm

app:
  push:
    board:
      url: https://dev.priros.co.kr/main/helpCenterNotice.rm

juso:
  api:
    key: U01TX0FVVEgyMDIxMDIwMzE3NTUyODExMDc3Nzc=

vender:
  send:
    url: https://test-dlaw.ktnet.com/new/market/%s/s
  link:
    url: https://dev.priros.co.kr

aligo:
  test:
    mode: N

nice:
  respond:
    sucess:
      url: https://dev.priros.co.kr/nice/checkSuccess.rm
    error:
      url: https://dev.priros.co.kr/nice/checkError.rm
  pay:
    mid: payutest1m
    key: Qo8sKAjtqnV5ttqqW9GKXzSmPos8Mh1+AoR1n94PquFR8otbIq9EjJFaYcJocN/bIcJqU10eNHRp6W6mWyqpWw==
    join:
      return:
        url: https://dev.priros.co.kr/nicePay/joinResult.rm
    regist:
      account:
        return:
          url: https://dev.priros.co.kr/nicePay/registAccountResult.rm
    auth:
      payment:
        return:
          url: https://dev.priros.co.kr/nicePay/authPaymentResult.rm
      common:
        payment:
          return:
            url: https://dev.priros.co.kr/nicePay/commonAuthPaymentResult.rm
    my:
      page:
        return:
          url: https://dev.priros.co.kr/nicePay/myPageResult.rm
    pay:
      process:
        return:
          url: https://dev.priros.co.kr/nicePay/payProcessResult.rm
  normal:
    pay:
      mid: nkeli2014m
      key: AqxSI4v9GacGBrCwzryOFNhMoprz2ZeaWWeH8kjDUQTO1OLS+vp

